services:
  app:
    build: .
    container_name: myapp_backend
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env
    depends_on:
      - mysql
      - redis
    restart: unless-stopped

  mysql:
    image: mysql:8.4
    container_name: myapp_mysql
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:7.4-alpine
    container_name: myapp_redis
    ports:
      - "6379:6379"
    volumes:
      - ./.docker/redis_data:/data